### ISSUE TITLE
请问这句的shape是不是不一致

### ISSUE THREAD

**Issue by Single430** [Zhihan1996/TradeTheEvent#1]
https://github.com/Zhihan1996/TradeTheEvent/blob/d346d38fa498ebe253430e1bcd31e13b8419bb50/utils/model.py#L81

你好，我理解的logits的shape = [BS, L, N]，pad_mask的shape = [BS, L]，所以计算是不是会报错？
如果我理解的不对，能否举个例子？

非常感谢 @Zhihan1996

**Comment by Zhihan1996** [comment]
你好，

我自己测试是没有问题的，你可以在这行code之前print一下每个变量各自的shape，可能会比较容易了解具体的计算
