### ISSUE TITLE
'BertConfig' object has no attribute 'max_seq_length'

### ISSUE THREAD

**Issue by pbohere** [Zhihan1996/TradeTheEvent#2]
thank you for such great work!!
I ran

`python run_event.py --TASK bilevel --data_dir ./data/Event_detection --epoch 5 --model_type models/bert_bc_adapted --output_dir models/bilevel --bert_lr 5e-5 --per_gpu_batch_size 8 --gradient_accumulation_steps 1 --max_seq_length 256`

I got the following error

`'BertConfig' object has no attribute 'max_seq_length'`

Adding the `"model_max_length": 256` attribute in the config file `models/bert_bc_adapted` can be a solution.

Would you please make a modification to the code and commit? 
Thank you very much!

**Comment by Zhihan1996** [comment]
Hi,

Thank you very much for pointing it out! Will solve it soon.
